export const states = [
  { id: "1", state_name: "ANDHRA PRADESH", country_id: "105", status: "1" },
  { id: "2", state_name: "ASSAM", country_id: "105", status: "1" },
  { id: "3", state_name: "ARUNACHAL PRADESH", country_id: "105", status: "1" },
  { id: "4", state_name: "BIHAR", country_id: "105", status: "1" },
  { id: "5", state_name: "GUJRAT", country_id: "105", status: "1" },
  { id: "6", state_name: "HARYANA", country_id: "105", status: "1" },
  { id: "7", state_name: "HIMACHAL PRADESH", country_id: "105", status: "1" },
  { id: "8", state_name: "JAMMU & KASHMIR", country_id: "105", status: "1" },
  { id: "9", state_name: "KARNATAKA", country_id: "105", status: "1" },
  { id: "10", state_name: "KERALA", country_id: "105", status: "1" },
  { id: "11", state_name: "MADHYA PRADESH", country_id: "105", status: "1" },
  { id: "12", state_name: "MAHARASHTRA", country_id: "105", status: "1" },
  { id: "13", state_name: "MANIPUR", country_id: "105", status: "1" },
  { id: "14", state_name: "MEGHALAYA", country_id: "105", status: "1" },
  { id: "15", state_name: "MIZORAM", country_id: "105", status: "1" },
  { id: "16", state_name: "NAGALAND", country_id: "105", status: "1" },
  { id: "17", state_name: "ORISSA", country_id: "105", status: "1" },
  { id: "18", state_name: "PUNJAB", country_id: "105", status: "1" },
  { id: "19", state_name: "RAJASTHAN", country_id: "105", status: "1" },
  { id: "20", state_name: "SIKKIM", country_id: "105", status: "1" },
  { id: "21", state_name: "TAMIL NADU", country_id: "105", status: "1" },
  { id: "22", state_name: "TRIPURA", country_id: "105", status: "1" },
  { id: "23", state_name: "UTTAR PRADESH", country_id: "105", status: "1" },
  { id: "24", state_name: "WEST BENGAL", country_id: "105", status: "1" },
  { id: "25", state_name: "DELHI", country_id: "105", status: "1" },
  { id: "26", state_name: "GOA", country_id: "105", status: "1" },
  { id: "27", state_name: "PONDICHERY", country_id: "105", status: "1" },
  { id: "28", state_name: "LAKSHDWEEP", country_id: "105", status: "1" },
  { id: "29", state_name: "DAMAN & DIU", country_id: "105", status: "1" },
  { id: "30", state_name: "DADRA & NAGAR", country_id: "105", status: "1" },
  { id: "31", state_name: "CHANDIGARH", country_id: "105", status: "1" },
  { id: "32", state_name: "ANDAMAN & NICOBAR", country_id: "105", status: "1" },
  { id: "33", state_name: "UTTARANCHAL", country_id: "105", status: "1" },
  { id: "34", state_name: "JHARKHAND", country_id: "105", status: "1" },
  { id: "35", state_name: "CHATTISGARH", country_id: "105", status: "1" },
];

export const cities = [
  { id: "515", city_name: "Agra", state_id: "23", tier_id: "1" },
  { id: "516", city_name: "Allahabad", state_id: "23", tier_id: "1" },
  { id: "517", city_name: "Aligarh", state_id: "23", tier_id: "1" },
  { id: "518", city_name: "Ambedkar Nagar", state_id: "23", tier_id: "1" },
  { id: "519", city_name: "Auraiya", state_id: "23", tier_id: "1" },
  { id: "520", city_name: "Azamgarh", state_id: "23", tier_id: "1" },
  { id: "521", city_name: "Barabanki", state_id: "23", tier_id: "1" },
  { id: "522", city_name: "Badaun", state_id: "23", tier_id: "1" },
  { id: "523", city_name: "Bagpat", state_id: "23", tier_id: "1" },
  { id: "524", city_name: "Bahraich", state_id: "23", tier_id: "1" },
  { id: "525", city_name: "Bijnor", state_id: "23", tier_id: "1" },
  { id: "526", city_name: "Ballia", state_id: "23", tier_id: "1" },
  { id: "527", city_name: "Banda", state_id: "23", tier_id: "1" },
  { id: "528", city_name: "Balrampur", state_id: "23", tier_id: "1" },
  { id: "529", city_name: "Bareilly", state_id: "23", tier_id: "1" },
  { id: "530", city_name: "Basti", state_id: "23", tier_id: "1" },
  { id: "531", city_name: "Bulandshahr", state_id: "23", tier_id: "1" },
  { id: "532", city_name: "Chandauli", state_id: "23", tier_id: "1" },
  { id: "533", city_name: "Chitrakoot", state_id: "23", tier_id: "1" },
  { id: "534", city_name: "Deoria", state_id: "23", tier_id: "1" },
  { id: "535", city_name: "Etah", state_id: "23", tier_id: "1" },
  { id: "536", city_name: "Kanshiram Nagar", state_id: "23", tier_id: "1" },
  { id: "537", city_name: "Etawah", state_id: "23", tier_id: "1" },
  { id: "538", city_name: "Firozabad", state_id: "23", tier_id: "1" },
  { id: "539", city_name: "Farrukhabad", state_id: "23", tier_id: "1" },
  { id: "540", city_name: "Fatehpur", state_id: "23", tier_id: "1" },
  { id: "541", city_name: "Faizabad", state_id: "23", tier_id: "1" },
  { id: "542", city_name: "Gautam Buddha Nagar", state_id: "23", tier_id: "1" },
  { id: "543", city_name: "Gonda", state_id: "23", tier_id: "1" },
  { id: "544", city_name: "Ghazipur", state_id: "23", tier_id: "1" },
  { id: "545", city_name: "Gorkakhpur", state_id: "23", tier_id: "1" },
  { id: "546", city_name: "Ghaziabad", state_id: "23", tier_id: "1" },
  { id: "547", city_name: "Hamirpur", state_id: "23", tier_id: "1" },
  { id: "548", city_name: "Hardoi", state_id: "23", tier_id: "1" },
  { id: "549", city_name: "Mahamaya Nagar", state_id: "23", tier_id: "1" },
  { id: "550", city_name: "Jhansi", state_id: "23", tier_id: "1" },
  { id: "551", city_name: "Jalaun", state_id: "23", tier_id: "1" },
  { id: "552", city_name: "Jyotiba Phule Nagar", state_id: "23", tier_id: "1" },
  { id: "553", city_name: "Jaunpur District", state_id: "23", tier_id: "1" },
  { id: "554", city_name: "Kanpur Dehat", state_id: "23", tier_id: "1" },
  { id: "555", city_name: "Kannauj", state_id: "23", tier_id: "1" },
  { id: "556", city_name: "Kanpur Nagar", state_id: "23", tier_id: "1" },
  { id: "557", city_name: "Kaushambi", state_id: "23", tier_id: "1" },
  { id: "558", city_name: "Kushinagar", state_id: "23", tier_id: "1" },
  { id: "559", city_name: "Lalitpur", state_id: "23", tier_id: "1" },
  { id: "560", city_name: "Lakhimpur Kheri", state_id: "23", tier_id: "1" },
  { id: "561", city_name: "Lucknow", state_id: "23", tier_id: "1" },
  { id: "562", city_name: "Mau", state_id: "23", tier_id: "1" },
  { id: "563", city_name: "Meerut", state_id: "23", tier_id: "1" },
  { id: "564", city_name: "Maharajganj", state_id: "23", tier_id: "1" },
  { id: "565", city_name: "Mahoba", state_id: "23", tier_id: "1" },
  { id: "566", city_name: "Mirzapur", state_id: "23", tier_id: "1" },
  { id: "567", city_name: "Moradabad", state_id: "23", tier_id: "1" },
  { id: "568", city_name: "Mainpuri", state_id: "23", tier_id: "1" },
  { id: "569", city_name: "Mathura", state_id: "23", tier_id: "1" },
  { id: "570", city_name: "Muzaffarnagar", state_id: "23", tier_id: "1" },
  { id: "571", city_name: "Pilibhit", state_id: "23", tier_id: "1" },
  { id: "572", city_name: "Pratapgarh", state_id: "23", tier_id: "1" },
  { id: "573", city_name: "Rampur", state_id: "23", tier_id: "1" },
  { id: "574", city_name: "Rae Bareli", state_id: "23", tier_id: "1" },
  { id: "575", city_name: "Saharanpur", state_id: "23", tier_id: "1" },
  { id: "576", city_name: "Sitapur", state_id: "23", tier_id: "1" },
  { id: "577", city_name: "Shahjahanpur", state_id: "23", tier_id: "1" },
  { id: "578", city_name: "Sant Kabir Nagar", state_id: "23", tier_id: "1" },
  { id: "579", city_name: "Siddharthnagar", state_id: "23", tier_id: "1" },
  { id: "580", city_name: "Sonbhadra", state_id: "23", tier_id: "1" },
  { id: "581", city_name: "Sant Ravidas Nagar", state_id: "23", tier_id: "1" },
  { id: "582", city_name: "Sultanpur", state_id: "23", tier_id: "1" },
  { id: "583", city_name: "Shravasti", state_id: "23", tier_id: "1" },
  { id: "584", city_name: "Unnao", state_id: "23", tier_id: "1" },
];
